server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/socialeggboxDB
  user: derekclark14
  password: smarti3pants
  #0=false; 1=true
  in_memory: 0